# Generated by Django 6.0.5 on 2026-05-14 12:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_usercopytraderhistory_custom_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='annual_amount',
            field=models.CharField(blank=True, choices=[('0-15k', 'Up to $15,000'), ('15k-50k', '$15,000 - $50,000'), ('50k-200k', '$50,000 - $200,000'), ('200k-500k', '$200,000 - $500,000'), ('500k-1m', '$500,000 - $1,000,000'), ('1m-3m', '$1,000,000 - $3,000,000'), ('3m+', 'Over $3,000,000')], help_text='Annual income (USD)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country_calling_code',
            field=models.CharField(blank=True, help_text='Country phone code (e.g., +1, +234)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='currency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='current_loyalty_status',
            field=models.CharField(choices=[('iron', 'Iron'), ('silver', 'Silver'), ('gold', 'Gold')], default='iron', help_text='Current loyalty tier', max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='estimated_net_worth',
            field=models.CharField(blank=True, choices=[('0-50k', 'Up to $50,000'), ('50k-100k', '$50,000 - $100,000'), ('100k-500k', '$100,000 - $500,000'), ('500k-1m', '$500,000 - $1,000,000'), ('1m-5m', '$1,000,000 - $5,000,000'), ('5m+', 'Over $5,000,000')], help_text='Estimated net worth (USD)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id_type',
            field=models.CharField(blank=True, choices=[('passport', 'Passport'), ('driver_license', "Driver's License"), ('national_id', 'National ID'), ('voter_card', "Voter's Card")], help_text='Select the type of ID provided', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='level_of_education',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate'), ('other', 'Other')], default='other', help_text='Highest level of education', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='next_loyalty_status',
            field=models.CharField(choices=[('iron', 'Iron'), ('silver', 'Silver'), ('gold', 'Gold')], default='silver', help_text='Next loyalty tier', max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, help_text="User's unique referral code", max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='source_of_income',
            field=models.CharField(blank=True, choices=[('salary', 'Salary'), ('business', 'Business'), ('investments', 'Investments'), ('pension', 'Pension'), ('savings', 'Savings'), ('inheritance', 'Inheritance'), ('other', 'Other')], help_text='Primary source of income', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status_of_employment',
            field=models.CharField(blank=True, choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('unemployed', 'Unemployed'), ('student', 'Student'), ('retired', 'Retired')], help_text='Employment status', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='title',
            field=models.CharField(blank=True, choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('ms', 'Ms.'), ('dr', 'Dr.'), ('prof', 'Prof.')], help_text='Title (Mr., Mrs., Ms., etc.)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(blank=True, help_text='4-digit verification code for email/2FA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
