# Generated by Django 6.0.5 on 2026-07-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_stock_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source_image_url',
            field=models.URLField(blank=True, help_text='External image URL from the news source/FMP (used when no image is uploaded above)', max_length=1000, null=True),
        ),
    ]
