# Generated by Django 6.0.5 on 2026-09-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_news_source_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='copy_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total capital currently being copied for this trader (AUM under copy), e.g. 15000000 for $15M', max_digits=20),
        ),
        migrations.AlterField(
            model_name='trader',
            name='risk',
            field=models.PositiveSmallIntegerField(default=5, help_text='Risk score should be from 1 to 10.'),
        ),
    ]
