# Generated by Django 6.0.5 on 2026-09-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_trader_copy_value_alter_trader_risk'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreemapStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('index', models.CharField(choices=[('dow30', 'Dow Jones 30')], default='dow30', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('change_percent', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('market_cap', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Treemap Stock',
                'verbose_name_plural': 'Treemap Stocks',
                'ordering': ['-market_cap'],
            },
        ),
    ]
