# Generated by Django 6.0.5 on 2026-09-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_treemapstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source_url',
            field=models.URLField(blank=True, help_text="Link to the original article on the source's site (powers 'Read full article')", max_length=1000, null=True),
        ),
    ]
