# Generated by Django 6.0.5 on 2026-09-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_news_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('prices', models.JSONField(default=list, help_text='Daily closes, oldest to newest')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock History',
                'verbose_name_plural': 'Stock History',
                'ordering': ['symbol'],
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='avg_volume',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='beta',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='div_yield',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Trailing dividend yield, as a percent (e.g. 0.45 = 0.45%)', max_digits=8),
        ),
        migrations.AddField(
            model_name='stock',
            name='domain',
            field=models.CharField(blank=True, help_text='Company website domain, e.g. apple.com (Clearbit logo fallback)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='eps',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stock',
            name='exchange',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='high_52w',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='stock',
            name='low_52w',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='stock',
            name='pe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
