# Generated by Django 6.0.5 on 2026-09-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_stockhistory_stock_avg_volume_stock_beta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='account_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
