# Generated by Django 6.0.5 on 2026-09-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_customuser_account_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='current_loyalty_status',
            field=models.CharField(choices=[('iron', 'Iron'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('elite', 'Elite')], default='iron', help_text='Current loyalty tier', max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='next_loyalty_status',
            field=models.CharField(choices=[('iron', 'Iron'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('elite', 'Elite')], default='silver', help_text='Next loyalty tier', max_length=200),
        ),
    ]
