# Generated by Django 6.0.5 on 2026-09-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_customuser_current_loyalty_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='make_royalty_program_visible',
            field=models.BooleanField(default=False, help_text="Admin-controlled gate for the Royalty Program tab on /market. While False, the tab's content is shown blurred with a locked notice overlaid; set to True once the user's capital meets the trader-assigned threshold to unlock it."),
        ),
    ]
