# Generated by Django 6.0.5 on 2026-09-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_customuser_make_royalty_program_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='blur_portfolio',
            field=models.BooleanField(default=True, help_text="If on, this trader's Portfolio tab is blurred for users until they unlock it by having at least the 'Blur portfolio amount' in their balance. If off, the portfolio is always visible."),
        ),
        migrations.AddField(
            model_name='trader',
            name='blur_portfolio_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Minimum user balance ($) required to view and mirror this trader's portfolio (only applies when 'Blur portfolio' is on)", max_digits=20),
        ),
    ]
