# Generated by Django 6.0.5 on 2026-09-24 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_trader_blur_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTraderPortfolioMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_at_unlock', models.DecimalField(decimal_places=2, default=0.0, help_text="User's balance when they unlocked the portfolio (for reference only)", max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trader', models.ForeignKey(help_text='Trader whose portfolio was unlocked', on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_mirrors', to='app.trader')),
                ('user', models.ForeignKey(help_text="User who unlocked the trader's portfolio", on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_mirrors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio Mirror',
                'verbose_name_plural': 'Portfolio Mirrors',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'trader')},
            },
        ),
    ]
