# Generated by Django 6.0.5 on 2026-09-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_usertraderportfoliomirror'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderportfolio',
            name='logo_url',
            field=models.URLField(blank=True, default='', help_text='Logo image URL. Leave blank to use the FMP logo for the ticker.', max_length=500),
        ),
        migrations.AddField(
            model_name='traderportfolio',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Company/asset name shown under the ticker. Example: Apple Inc.', max_length=200),
        ),
    ]
