# Generated by Django 6.0.5 on 2026-10-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_trader_blur_portfolio_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='blur_portfolio_amount',
            field=models.DecimalField(decimal_places=2, default=1000000.0, help_text="Minimum user balance ($) required to view and mirror this trader's portfolio (only applies when 'Blur portfolio' is on)", max_digits=20),
        ),
    ]
